version: "3.7"

services:
  web:
    build: .
    volumes:
      - static_volume:/api/static
    networks:
      - nginx_network

  nginx:
    image: nginx:1.15.7-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/api/static:ro
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume:
